---
name: github_rule
description: Receive Github repo updates & trigger an action
enabled: true

trigger:
  type: git.head_sha_monitor

action:
  ref: stackstorm.github_action
  parameters: 
    payload: "{{ trigger }}"
